language: python

install:
#  - pip install travis-sphinx
#  - export PATH=$HOME/.local/bin:$PATH
   - pip install sphinx
   - pip install sphinx_rtd_theme
   - pip install bibtexparser
   - pip install pprint
#   - sudo apt-get install python3-sphinx

script:
  # Update paper list 
  - python bibtex2rst.py
  # Use Sphinx to make the html docs
  - make html
  # Tell GitHub not to use jekyll to compile the docs
  - touch _build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  fqdn: wiki.continualai.org
  github_token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: _build/html/
    
after_success:
    - travis-sphinx deploy
